---
- hosts: dev
  tasks:
    - name: Start the container
      docker_container:
        name: test
        image: "thelazycode/simpleapp:031d6d5"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
